volumes:
  redis-data:
  bff-message-target:

secrets:
  npmrc:
    file: ./.npmrc
  node_auth_token:
    environment: NODE_AUTH_TOKEN

networks:
  backend:
  user_backend:
    external: true
    name: ${USER_BACKEND_NETWORK:-bff_user_backend}

x-common-env: &common-env
  HOST: "0.0.0.0"
  PORT: 4003
  REDIS_URL: redis://redis:6379
  DB_TYPE: postgres
  DB_NAME: mairie_360_database
  DB_USER: postgres
  DB_HOST: ${SHARED_DB_HOST:-mairie360-db-bff-user}
  DB_PASSWORD: password
  DB_PORT: 5432

x-depends-on: &depends-on
  redis:
    condition: service_healthy

# x-healthcheck: &healthcheck
#   test: ["CMD", "curl", "-f", "http://localhost:4003"]
#   interval: 10s
#   timeout: 5s
#   retries: 5

x-service: &service-template
  image: ghcr.io/mairie360/service_name:latest
  pull_policy: always
  restart: always
  expose:
    - "4003"
  networks:
    - backend
  # healthcheck:
  #   <<: *healthcheck

services:
  redis:
    image: redis:8.4.0-bookworm
    container_name: mairie360-redis-message-bff #change bff name
    restart: always
    expose:
      - "6379"
    volumes:
      - redis-data:/data
    networks:
      - backend
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  message-api:
    container_name: message-api-bff-message-developpement
    image: ghcr.io/mairie360/message-api:0.5.0
    ports:
      - "3003:3003"
    networks:
      - backend
      - user_backend
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      HOST: "0.0.0.0"
      PORT: 3003
      REDIS_URL: redis://redis:6379
      DB_TYPE: postgres
      DB_NAME: mairie_360_database
      DB_USER: postgres
      DB_HOST: ${SHARED_DB_HOST:-mairie360-db-bff-user}
      DB_PASSWORD: password
      DB_PORT: 5432
      PUBLIC_URL: http://message.development.mairie360.fr
      JWT_SECRET: b"secret"
      JWT_TIMEOUT: 3600
    depends_on:
      <<: *depends-on
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:3003/health"] # <--- Doit être 3003
    #   interval: 5s
    #   timeout: 2s
    #   retries: 3
    #   start_period: 10s

  #add other apis if needed

  bff-message:
    container_name: bff-message-developpement
    build:
      context: .
      dockerfile: development.Dockerfile
      secrets:
        - npmrc
        - node_auth_token
    # Mode synchronisation en temps réel (Docker Compose V2)
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
        - action: rebuild
          path: package.json
    ports:
      - "4003:4003"
    networks:
      - backend
      - user_backend
    environment:
      <<: *common-env
      # IMPORTANT : On utilise le nom du service Docker pour communiquer
      CORE_API_URL: "core"
      CORE_API_PORT: 3000
      MESSAGE_API_URL: "message-api"
      MESSAGE_API_PORT: 3003
      MESSAGE_API_BASE_PATH: "http://message-api:3003/api"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /app/node_modules # Isolation des modules pour éviter les conflits OS (Mac/Windows vs Linux)
    # depends_on:
    # core:
    #   condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4003/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  # nginx:
  #   image: nginx:1.27.4-bookworm
  #   restart: always
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   ports:
  #     - "80:80"
  #   networks:
  #     - backend
  #   depends_on:
  #     bff-message: #change bff name
  #       condition: service_healthy
