import http from 'k6/http';
import { check, sleep } from 'k6';
import crypto from 'k6/crypto';
import encoding from 'k6/encoding';
import { createCoverage } from '/coverage.js';

// ---------------------------------------------------------------------------
// k6 load test of the BFF Message.
//
// Every operation of the contract (contracts/openapi.json, mounted as /openapi.json) has one
// handler below: the shared OpenAPI coverage module (mairie360/CICD tests/k6/coverage.js, see
// performance_test.sh) aborts at init when an operation has no handler, and fails the
// `operations_uncovered` threshold when a handler ends without sending its request. Adding a route
// to the BFF therefore means adding its handler here.
//
// Two scenarios share the handlers:
// - `crud` (2 VUs): `coverage.run()` calls every handler once per iteration, reads and writes, so
//   it carries the coverage gate. Handlers run path by path in contract order and, for one path,
//   in the order get, put, post, delete, options, head, patch, trace. DELETE /conversations/{id}
//   comes before POST /groups in the contract, so its handler first creates the group it deletes.
//   The group and the direct message created later are kept in `state` and deleted by `cleanup()`
//   at the end of the iteration.
// - `reads` (up to 20 VUs): replays only the GET handlers, which read the fixtures seeded by
//   init-test.sql (conversation 101, message 1001) and never depend on `state`.
// Every operation gets a p(95) threshold, whose budget depends on its family (`budgetOf`).
//
// MAIR-474: the stack also runs init-perf.sql (Message_API's seed: 2 000 agents in 4 000 group chats and
// 1 000 direct chats, 25 messages per group chat, 10 000 in the hot chat 100000). The reads run as random
// agents and check their own profile, chats and messages; `conversations_rush` sends `GET /conversations`
// at a fixed rate; thresholds are strict (every check passes, no failed request, no dropped iteration).
// K6_PROFILE sizes the load: `ci` (default, 4 vCPU CI runner) or `stress` (by hand).
// ---------------------------------------------------------------------------

// The JWT_SECRET of the APIs and this BFF in the test stack: random per run, generated by stack_secrets.sh
// (MAIR-474). No default: nothing is signed with a committed secret.
const JWT_SECRET = __ENV.JWT_SECRET;
if (!JWT_SECRET) throw new Error('JWT_SECRET is not set: run ./performance_test.sh, which generates it');
// Rows of init-perf.sql: agent 400001 + r is a member of the group chat 100000 + r (25 messages, 10 000
// for r = 0) and of 15 other group chats.
const AGENTS = { first: 400001, count: 2000 };

const PROFILES = {
  ci: { readVus: 30, crudVus: 2, rushRate: 30 },
  stress: { readVus: 100, crudVus: 4, rushRate: 100 },
};
const PROFILE = PROFILES[__ENV.K6_PROFILE || 'ci'];
if (!PROFILE) throw new Error(`Unknown K6_PROFILE ${__ENV.K6_PROFILE}: ${Object.keys(PROFILES).join(', ')}`);
// User seeded by init-test.sql (JWT sub), member of the fixture conversation 101.
const USER_ID = __ENV.PERF_USER_ID || '2';
// Fixtures seeded by init-test.sql.
const FIXTURE_CONVERSATION = 'conversation-101';
const FIXTURE_MESSAGE = 'message-1001';
const CONTACT_ID = 'user-3';

// State of the current iteration (module scope is per VU in k6).
let state = {};

function b64url(value) {
  return encoding.b64encode(value, 'rawurl');
}

// Minimal HS256 JWT accepted by Message API and Core API (sub + role + exp claims).
function mintJwt(sub) {
  const header = b64url(JSON.stringify({ alg: 'HS256', typ: 'JWT' }));
  const now = Math.floor(Date.now() / 1000);
  const payload = b64url(JSON.stringify({ sub, role: 'user', exp: now + 3600 }));
  const signingInput = `${header}.${payload}`;
  const signature = crypto.hmac('sha256', JWT_SECRET, signingInput, 'base64rawurl');
  return `${signingInput}.${signature}`;
}

const agentTokens = {};
/** A random seeded agent: its id, `Authorization` header and the group chat it is sure to be in. */
function randomAgent() {
  const rank = Math.floor(Math.random() * AGENTS.count);
  const id = AGENTS.first + rank;
  if (!agentTokens[id]) agentTokens[id] = { Authorization: `Bearer ${mintJwt(String(id))}` };
  return { id, rank, headers: agentTokens[id], chat: `conversation-${100000 + rank}` };
}

function body(response) {
  try {
    return response.json();
  } catch (_) {
    return {};
  }
}

const isAgent = (user, agent) => (user || {}).id === `user-${agent.id}`;

function unique(prefix) {
  return `${prefix} ${__VU}-${__ITER}-${Date.now()}`;
}

function need(value, what) {
  if (value === undefined || value === null) {
    throw new Error(`${what} is missing, an earlier handler of this iteration failed`);
  }
  return value;
}

function json(response) {
  try {
    return response.json();
  } catch (_) {
    return null;
  }
}

function conversationIdOf(response) {
  const body = json(response) || {};
  return body.conversation ? body.conversation.id : undefined;
}

function groupBody(name) {
  return { name, description: 'k6 group', memberIds: [CONTACT_ID] };
}

// Operations that are not available yet answer 503 by design: not counted in http_req_failed.
const UNAVAILABLE_IS_EXPECTED = http.expectedStatuses(503);

// POST /attachments takes multipart/form-data: the string body is sent as is by coverage.js.
const BOUNDARY = 'k6-attachment-boundary';
const ATTACHMENT_BODY =
  `--${BOUNDARY}\r\n` +
  'Content-Disposition: form-data; name="files"; filename="k6.txt"\r\n' +
  'Content-Type: text/plain\r\n\r\n' +
  'k6 attachment\r\n' +
  `--${BOUNDARY}--\r\n`;

const handlers = {
  // --- Connectivity (public) ---
  'GET /health': ({ request }) =>
    check(request(), { 'health 200': (r) => r.status === 200 }),
  'GET /check_apis': ({ request }) =>
    check(request(), { 'check_apis 200': (r) => r.status === 200 }),

  // --- Reads ---
  // BFF Project / BFF Calendar are not part of the stack: the route degrades per source and
  // still answers 200.
  'GET /business-references': ({ request }) =>
    check(request(), { 'business-references 200': (r) => r.status === 200 }),
  'GET /messaging/bootstrap': ({ request }) => {
    const agent = randomAgent();
    check(request({ headers: agent.headers }), {
      'bootstrap 200': (r) => r.status === 200,
      'bootstrap is the agent with its chats': (r) =>
        r.status === 200 && isAgent(body(r).currentUser, agent) && (body(r).conversations || []).length > 0,
    });
  },
  'GET /contacts': ({ request }) => {
    const agent = randomAgent();
    check(request({ query: { limit: 20 }, headers: agent.headers }), {
      'contacts 200': (r) => r.status === 200,
    });
  },
  // A page of 20 (the 16 chats of the agent), a page of 5 that must hand over a cursor, or a search by the full name
  // of a member the agent shares chat `100000 + rank` with (MAIR-507): all served by ONE Message API call.
  'GET /conversations': ({ request }) => {
    const agent = randomAgent();
    const kind = Math.floor(Math.random() * 3);
    if (kind === 0) {
      const coMember = AGENTS.first + ((agent.rank + 250) % AGENTS.count);
      check(request({ query: { search: `Agent Perf ${coMember}` }, headers: agent.headers }), {
        'search conversations 200': (r) => r.status === 200,
        'search conversations finds the chat shared with the member': (r) =>
          r.status === 200 && (body(r).conversations || []).some((conversation) => conversation.id === agent.chat),
      });
    } else if (kind === 1) {
      check(request({ query: { limit: 5 }, headers: agent.headers }), {
        'conversations page 200': (r) => r.status === 200,
        'conversations page hands over the next cursor': (r) =>
          r.status === 200 && (body(r).conversations || []).length === 5 && body(r).nextCursor === '5',
      });
    } else {
      checkConversations(request({ query: { limit: 20 }, headers: agent.headers }), 'conversations');
    }
  },
  // Opens one of the agent's group chats: its 8 members with their names and the 25 seeded messages (MAIR-507).
  'GET /conversations/{conversationId}': ({ request }) => {
    const agent = randomAgent();
    check(request({ path: { conversationId: agent.chat }, headers: agent.headers }), {
      'load conversation 200': (r) => r.status === 200,
      'load conversation carries the members and the messages': (r) => {
        if (r.status !== 200) return false;
        const loaded = body(r);
        return loaded.conversation.id === agent.chat
          && loaded.participants.length === 8
          && loaded.participants.every((participant) => participant.name.startsWith('Agent Perf '))
          && loaded.messages.length >= 25
          && loaded.messages.every((message) => message.authorName && message.authorId);
      },
    });
  },
  'GET /me': ({ request }) => {
    const agent = randomAgent();
    check(request({ headers: agent.headers }), {
      'me 200': (r) => r.status === 200,
      'me is the agent': (r) => r.status === 200 && isAgent(body(r).currentUser, agent),
    });
  },
  // The first page of one of the agent's group chats (the hot chat 100000 for agent 400001).
  'GET /conversations/{conversationId}/messages': ({ request }) => {
    const agent = randomAgent();
    check(request({ path: { conversationId: agent.chat }, query: { limit: 20 }, headers: agent.headers }), {
      'messages 200': (r) => r.status === 200,
      'messages read the agent chat': (r) => r.status === 200 && (body(r).messages || []).length === 20,
    });
  },

  // --- Writes ---
  'POST /attachments': ({ request }) =>
    // No attachment storage exists upstream yet: the BFF answers 503 instead of made-up ids (MAIR-400).
    check(request({
      body: ATTACHMENT_BODY,
      headers: { 'Content-Type': `multipart/form-data; boundary=${BOUNDARY}` },
      params: { responseCallback: UNAVAILABLE_IS_EXPECTED },
    }), {
      'attachments 503': (r) => r.status === 503,
    }),
  // Runs before POST /groups: creates the group it deletes.
  'DELETE /conversations/{conversationId}': ({ request, data }) => {
    const created = http.post(coverage.url('POST /groups'), JSON.stringify(groupBody(unique('k6 deleted group'))), {
      headers: Object.assign({ 'Content-Type': 'application/json' }, data.user),
      tags: { op: 'POST /groups' },
    });
    check(created, { 'create group 201': (r) => r.status === 201 });
    check(request({ path: { conversationId: need(conversationIdOf(created), 'disposable group') } }), {
      'delete conversation 200': (r) => r.status === 200,
    });
  },
  'POST /conversations/{conversationId}/read': ({ request }) =>
    check(request({
      path: { conversationId: FIXTURE_CONVERSATION },
      // Seeded message of conversation 101, of which user 2 is a member (init-test.sql).
      body: { readUntilMessageId: FIXTURE_MESSAGE },
    }), {
      'read 200': (r) => r.status === 200,
    }),
  'POST /groups': ({ request }) => {
    const res = request({ body: groupBody(unique('k6 group')) });
    check(res, { 'create group 201': (r) => r.status === 201 });
    state.groupId = conversationIdOf(res);
  },
  'POST /conversations/{conversationId}/messages': ({ request }) =>
    check(request({ path: { conversationId: need(state.groupId, 'created group') }, body: { content: 'k6 message', mentionIds: [CONTACT_ID] } }), {
      'send message 201': (r) => r.status === 201,
    }),
  // The BFF reuses the caller's direct conversation with the recipient, and cleanup() leaves it: every
  // crud VU writes to its own recipient (the last seeded agents), so a VU never sends to the
  // conversation another VU has just left.
  'POST /direct-messages': ({ request }) => {
    const recipientId = `user-${AGENTS.first + AGENTS.count - __VU}`;
    const res = request({ body: { recipientId, message: 'k6 direct message' } });
    check(res, { 'direct message 201': (r) => r.status === 201 });
    state.directId = conversationIdOf(res);
  },
};

const coverage = createCoverage(handlers);
const readOperations = coverage.operations.filter((o) => o.method === 'GET');

// Deletes the conversations kept by the handlers, so that the listings do not grow during the test.
function cleanup(data) {
  for (const conversationId of [state.groupId, state.directId]) {
    if (!conversationId) continue;
    http.del(coverage.url('DELETE /conversations/{conversationId}', { conversationId }), null, {
      headers: data.user,
      tags: { op: 'DELETE /conversations/{conversationId}' },
    });
  }
}

// p(95) budget of an operation, per family.
function budgetOf({ op, method }) {
  if (op === 'GET /health') return 50; // process probe
  if (op === 'GET /check_apis') return 150; // -> Message API / Core API /health
  if (method === 'GET') return 400; // BFF aggregation + upstream reads
  return 800; // writes
}

const perOperationThresholds = {};
for (const operation of coverage.operations) {
  perOperationThresholds[`http_req_duration{op:${operation.op}}`] = [`p(95)<${budgetOf(operation)}`];
}

/** An agent's chat list: a full first page (every agent is in 16 group chats and some direct ones). */
function checkConversations(response, prefix) {
  return check(response, {
    [`${prefix} 200`]: (r) => r.status === 200,
    [`${prefix} lists the agent chats`]: (r) => r.status === 200 && (body(r).conversations || []).length >= 16,
  });
}

export const options = {
  scenarios: {
    reads: {
      executor: 'ramping-vus',
      exec: 'reads',
      stages: [
        { duration: '30s', target: Math.ceil(PROFILE.readVus / 2) }, // ramp-up
        { duration: '30s', target: PROFILE.readVus },
        { duration: '2m', target: PROFILE.readVus }, // steady load
        { duration: '20s', target: 0 }, // ramp-down
      ],
    },
    crud: {
      executor: 'constant-vus',
      exec: 'crud',
      vus: PROFILE.crudVus,
      duration: '3m20s',
    },
    conversations_rush: {
      executor: 'constant-arrival-rate',
      exec: 'conversationsRush',
      startTime: '1m', // once the reads are at their peak
      rate: PROFILE.rushRate,
      timeUnit: '1s',
      duration: '1m',
      preAllocatedVUs: 30,
      maxVUs: 200,
    },
  },
  thresholds: {
    ...coverage.thresholds,
    ...perOperationThresholds,
    'http_req_duration{op:conversations_rush}': ['p(95)<400'],
    dropped_iterations: ['count==0'], // the rush kept its rate
    // Strict (MAIR-474): one wrong status, one wrong row or one failed request fails the run.
    http_req_failed: ['rate==0'],
    checks: ['rate==1'],
  },
};

export function setup() {
  return { user: { Authorization: `Bearer ${mintJwt(USER_ID)}` } };
}

// Every GET handler, with a plain request() (no coverage accounting: `crud` owns the gate).
export function reads(data) {
  for (const operation of readOperations) {
    const request = (call = {}) =>
      http.get(coverage.url(operation.op, call.path, call.query), {
        headers: Object.assign({}, data.user, call.headers),
        tags: { op: operation.op },
      });
    handlers[operation.op]({ request, data, op: operation.op, method: operation.method, path: operation.path });
  }
  sleep(1);
}

export function conversationsRush() {
  const agent = randomAgent();
  checkConversations(
    http.get(coverage.url('GET /conversations', {}, { limit: 20 }), { headers: agent.headers, tags: { op: 'conversations_rush' } }),
    'rush conversations',
  );
}

export function crud(data) {
  state = {};
  coverage.run({ headers: data.user, data });
  cleanup(data);
  sleep(1);
}
